package main

import (
	"encoding/json"
	"fmt"
)

// cool website
// https://mholt.github.io/json-to-go/

// from:
// [{"First":"James","Last":"Bond","Age":32},{"First":"Miss","Last":"Moneypenny","Age":27}]

// to:
// type AutoGenerated []struct {
// 	First string `json:"First"`
// 	Last  string `json:"Last"`
// 	Age   int    `json:"Age"`
// }

type person struct {
	First string `json:"First"`
	Last  string `json:"Last"`
	Age   int    `json:"Age"`
}

func main() {
	s := `[{"First":"James","Last":"Bond","Age":32},{"First":"Miss","Last":"Moneypenny","Age":27}]`
	bs := []byte(s)
	fmt.Printf("%T\n", s)
	fmt.Printf("%T\n", bs) // []uint8 == []bytes
	var people []person
	// people := []person{} <-- same but above is clearer

	err := json.Unmarshal(bs, &people)
	if err != nil {
		fmt.Println(err)
	}
	fmt.Println("\nThis is the data", people)

	for i, v := range people {
		fmt.Println("\n Person Number:", i+1)
		fmt.Println(v.First)
		fmt.Println(v.Last)
		fmt.Println(v.Age)

	}
}
